### ISSUE TITLE
Add chmod override config option

### ISSUE THREAD

**Issue by jamestomasino** [jamestomasino/burrow#24]
Add an option to specify a chmod for new posts & gophermaps. If it's set, after creating or updating a file chmod it automatically. This would be helpful for systems with odd umask settings.

**Comment by benharri** [comment]
To expand on this a bit, my umask is currently 0022. new files are created 644 without running `burrow phlog`.

**Comment by jamestomasino** [comment]
This has been addressed by properly creating files with touch and catting contents from tempfiles instead of copying tempfiles, which didn't respect umask.

Fixed in 1.5.1
