### ISSUE TITLE
Makefile failing on FreeBSD due to bash completion and make version

### ISSUE THREAD

**Issue by Munchotaur** [jamestomasino/burrow#33]
Make just fell over on FreeBSD 12.0. These three steps worked:

1. Installing bash-completion via either `pkg install bash-completion` or via the `shells/bash-completion` port. (The first worked fine for me and was the simpler route).
2. Installing the GNU version of make via either `pkg install gmake` or the port `devel/gmake`.
3. Rather than running `sudo make install`, run `sudo gmake install`.

Maybe these could be added to the installation guidelines?

**Comment by jamestomasino** [comment]
Added instructions to readme. Maybe we'll figure out how to make a single happy makefile one day.
